/* =========================================================
   SERVICE WORKER — installable, offline-first app shell

   Three caches, each with its own rule:

   - shell-<VERSION>: every file the planner needs to boot
     (HTML, CSS, JS modules, Leaflet, icons). Precached on
     install, served cache-first, and swapped wholesale when a
     new VERSION ships — activate deletes every other shell-*.
     VERSION and SHELL are written by scripts/build-sw.mjs from
     a hash of those files, so any change to any of them
     changes this file, which is what makes the browser see an
     update at all. Run it before committing shell changes.
   - fonts: Google Fonts CSS + font files, cached as they're
     used (stale-while-revalidate), so text keeps its faces
     offline.
   - photos-<room>: stop photos for the last few trips opened,
     filled on the page's request (js/pwa.js) rather than as a
     side effect of browsing, so what's kept is exactly "this
     trip's photos" and old trips can be dropped as a unit.

   Deliberately NOT handled — they go straight to the network:
   map tiles and routing (known v1 limitation), Firebase,
   geocoding, and any CORS-mode fetch. That last one matters:
   the "Take this trip offline" export fetches photos in CORS
   mode to re-encode them, and must never be handed an opaque
   cached copy it can't read.
   ========================================================= */

// ---- generated by scripts/build-sw.mjs — do not edit by hand ----
const VERSION = '3c064fcd5fba';
const SHELL = [
  'index.html',
  'manifest.json',
  'css/main.css',
  'js/app.js',
  'js/cloud.js',
  'js/config.js',
  'js/exporters.js',
  'js/format.js',
  'js/geocode.js',
  'js/img.js',
  'js/llm.js',
  'js/offline.js',
  'js/optimize.js',
  'js/pwa.js',
  'js/routing.js',
  'js/schedule.js',
  'js/state.js',
  'js/ui.js',
  'js/util.js',
  'vendor/leaflet/leaflet.css',
  'vendor/leaflet/leaflet.js',
  'vendor/leaflet/images/layers-2x.png',
  'vendor/leaflet/images/layers.png',
  'vendor/leaflet/images/marker-icon-2x.png',
  'vendor/leaflet/images/marker-icon.png',
  'vendor/leaflet/images/marker-shadow.png',
  'icons/apple-touch-icon.png',
  'icons/icon-192.png',
  'icons/icon-512.png',
  'icons/icon-maskable-192.png',
  'icons/icon-maskable-512.png',
  'demo/rome-venice-trip.md',
];
// ---- end generated ----

const SHELL_CACHE = 'shell-' + VERSION;
const FONT_CACHE = 'fonts';
const PHOTO_PREFIX = 'photos-';
const FONT_HOSTS = ['fonts.googleapis.com', 'fonts.gstatic.com'];

/* The pages the shell answers for. Any query string (?source=pwa,
   ?newTrip=1) is ignored: the hash carries the trip, not the path. */
const SCOPE = new URL('./', self.location).href;
const PAGE_URLS = new Set([SCOPE, SCOPE + 'index.html']);
const SHELL_SET = new Set(SHELL.map(u => new URL(u, SCOPE).href));

self.addEventListener('install', (event) => {
  event.waitUntil((async () => {
    const cache = await caches.open(SHELL_CACHE);
    // cache:'reload' skips the HTTP cache: GitHub Pages lets browsers keep
    // files for 10 minutes, and a new version must not precache old ones.
    await cache.addAll(SHELL.map(u => new Request(u, { cache: 'reload' })));
  })());
  // No skipWaiting here: the page decides when a new version takes over
  // (a "Reload" banner now, or the next launch) — see js/pwa.js.
});

self.addEventListener('activate', (event) => {
  event.waitUntil((async () => {
    const names = await caches.keys();
    await Promise.all(names
      .filter(n => n.startsWith('shell-') && n !== SHELL_CACHE)
      .map(n => caches.delete(n)));
    await self.clients.claim();
  })());
});

self.addEventListener('message', (event) => {
  const msg = event.data || {};
  if(msg.type === 'skip-waiting') self.skipWaiting();
  else if(msg.type === 'cache-photos') event.waitUntil(cachePhotos(msg));
  else if(msg.type === 'keep-photos') event.waitUntil(prunePhotos(msg.keep || []));
});

self.addEventListener('fetch', (event) => {
  const req = event.request;
  if(req.method !== 'GET') return;
  const url = new URL(req.url);

  if(req.mode === 'navigate'){
    const bare = url.origin + url.pathname;
    if(PAGE_URLS.has(bare)) event.respondWith(shellFirst(req, SCOPE + 'index.html'));
    return;                                   // admin.html and anything else: network
  }

  if(url.origin === self.location.origin){
    const bare = url.origin + url.pathname;
    if(SHELL_SET.has(bare)) event.respondWith(shellFirst(req, bare));
    return;
  }

  if(FONT_HOSTS.includes(url.hostname)){
    event.respondWith(staleWhileRevalidate(req, FONT_CACHE));
    return;
  }

  // Photos: only plain <img> loads (no-cors). A CORS fetch — the offline
  // export's — always goes to the network untouched.
  if(req.destination === 'image' && req.mode === 'no-cors'){
    event.respondWith(photoFirst(req));
  }
});

/* Cache-first for the app shell, falling back to the network only when a
   file is missing from the cache (a first visit racing the install). */
async function shellFirst(req, key){
  const cache = await caches.open(SHELL_CACHE);
  const hit = await cache.match(key, { ignoreSearch: true });
  if(hit) return hit;
  return fetch(req);
}

async function staleWhileRevalidate(req, name){
  const cache = await caches.open(name);
  const hit = await cache.match(req);
  const fresh = fetch(req).then(res => {
    if(res && (res.ok || res.type === 'opaque')) cache.put(req, res.clone());
    return res;
  }).catch(() => null);
  return hit || (await fresh) || Response.error();
}

/* A cached photo if any trip holds one; otherwise the network, untouched.
   Nothing is stored here — map tiles come through this path too, and only
   the page's explicit cache-photos list decides what's kept. */
async function photoFirst(req){
  const names = (await caches.keys()).filter(n => n.startsWith(PHOTO_PREFIX));
  for(const n of names){
    const hit = await (await caches.open(n)).match(req.url);
    if(hit) return hit;
  }
  return fetch(req);
}

/* { room, urls, keep } — store every url for this room (skipping ones
   already held), drop the room's photos no longer in the trip, and delete
   whole caches for rooms that fell out of the recent list. */
async function cachePhotos({ room, urls, keep }){
  if(!room || !Array.isArray(urls)) return;
  const cache = await caches.open(PHOTO_PREFIX + room);
  const want = new Set(urls);
  for(const req of await cache.keys()){
    if(!want.has(req.url)) await cache.delete(req);
  }
  for(const u of want){
    if(await cache.match(u)) continue;
    const res = await fetchPhoto(u);
    if(res) await cache.put(u, res);
  }
  if(Array.isArray(keep)) await prunePhotos(keep);
}

/* CORS first — a readable response costs its real size against the
   storage quota — and an opaque no-cors copy for hosts that don't send
   CORS headers, which an <img> can still show. */
async function fetchPhoto(u){
  const opts = { referrerPolicy: 'no-referrer', credentials: 'omit' };
  try{
    const res = await fetch(u, { ...opts, mode: 'cors' });
    if(res.ok) return res;
  } catch(e){}
  try{
    const res = await fetch(u, { ...opts, mode: 'no-cors' });
    if(res.type === 'opaque' || res.ok) return res;
  } catch(e){}
  return null;
}

async function prunePhotos(keep){
  const keepSet = new Set(keep.map(r => PHOTO_PREFIX + r));
  const names = await caches.keys();
  await Promise.all(names
    .filter(n => n.startsWith(PHOTO_PREFIX) && !keepSet.has(n))
    .map(n => caches.delete(n)));
}
