#!/usr/bin/env node
/* Stamp sw.js with the app shell's file list and a content hash.

   The browser only notices a new service worker when sw.js itself changes
   byte-for-byte, so the version has to live in that file. This hashes every
   shell file and rewrites the generated block at the top of sw.js: change
   any shell file, re-run this, and installed apps pick the update up.

   Run:   node scripts/build-sw.mjs          (rewrite sw.js)
          node scripts/build-sw.mjs --check  (exit 1 if sw.js is stale — CI) */

import { readFileSync, writeFileSync, readdirSync, existsSync } from 'node:fs';
import { createHash } from 'node:crypto';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';

const root = join(dirname(fileURLToPath(import.meta.url)), '..');
const ls = (dir, re) => readdirSync(join(root, dir)).filter(f => re.test(f)).sort().map(f => dir + '/' + f);

/* Everything index.html needs to boot and run. admin.html / js/admin.js are
   left out on purpose: the rooms dashboard is an online-only tool. */
const SHELL = [
  'index.html',
  'manifest.json',
  'css/main.css',
  ...ls('js', /\.js$/).filter(f => f !== 'js/admin.js'),
  'vendor/leaflet/leaflet.css',
  'vendor/leaflet/leaflet.js',
  ...ls('vendor/leaflet/images', /\.png$/),
  ...ls('icons', /\.png$/),
  'demo/rome-venice-trip.md',
];

for(const f of SHELL){
  if(!existsSync(join(root, f))){ console.error('build-sw: missing shell file ' + f); process.exit(1); }
}

const hash = createHash('sha256');
for(const f of SHELL){ hash.update(f + '\0'); hash.update(readFileSync(join(root, f))); hash.update('\0'); }
const version = hash.digest('hex').slice(0, 12);

const START = '// ---- generated by scripts/build-sw.mjs — do not edit by hand ----\n';
const END = '// ---- end generated ----\n';
const block = START +
  `const VERSION = '${version}';\n` +
  'const SHELL = [\n' + SHELL.map(f => `  '${f}',\n`).join('') + '];\n' +
  END;

const swPath = join(root, 'sw.js');
const sw = readFileSync(swPath, 'utf8');
const a = sw.indexOf(START), b = sw.indexOf(END);
if(a < 0 || b < a){ console.error('build-sw: generated markers not found in sw.js'); process.exit(1); }
const next = sw.slice(0, a) + block + sw.slice(b + END.length);

if(process.argv.includes('--check')){
  if(next !== sw){
    console.error('sw.js is stale — run `node scripts/build-sw.mjs` and commit the result.');
    process.exit(1);
  }
  console.log('sw.js is up to date (' + version + ').');
} else {
  if(next !== sw) writeFileSync(swPath, next);
  console.log('sw.js stamped: ' + version + ' (' + SHELL.length + ' shell files)');
}
